version: 2

sources:
  - name: Data Warehouse
    description: "data warehouse"
    database: vehicle_db
    schema: public
    tables:
      - name: vehicle
        description: "Vehicles table"
        columns:
          - name: id # required
            description: unique identifier for the vehicle
          - name: track_id
            description: id of the track
          - name: vehicle_type
            description: type of the vehicle
          - name: traveled_d
            description: distance traveled by the vehicle
          - name: avg_speed
            description: average speed of the vehicle
          - name: lat
            description: latitude of the vehicle
          - name: lon
            description: longitude of the vehicle
          - name: speed
            description: speed of the vehicle at the given time
          - name: loan_acc
            description: loan account of the vehicle
          - name: lat_acc
            description: latitude of the vehicle at the given time
          - name: record_time
            description: time of the clear
            record